language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t udagram-api-user ./project/udagram-api-user
  - docker tag udagram-api-user karolose/udagram-api-user:latest
  - docker build -t udagram-api-feed ./project/udagram-api-feed
  - docker tag udagram-api-feed karolose/udagram-api-feed:latest
  - docker build -t udagram-frontend ./project/udagram-frontend
  - docker tag udagram-frontend karolose/udagram-frontend:latest

after_success:
  - docker login --username "$DOCKER_USERNAME" --password "$DOCKER_PASSWORD"
  - docker push karolose/udagram-api-user
  - docker push karolose/udagram-api-feed
  - docker push karolose/udagram-frontend